### ISSUE TITLE
Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

### ISSUE THREAD

**Issue by dorkbox** [dorkbox/SystemTray#19]
This is an issue on some later versions of GNOME (3.18.4+, unknown when exactly this appears), and specifically on Fedora 23.

It is unknown why this error appears - however everything seems to function correctly even though it is happening. I am open to suggestions as to how to fix this.

**Comment by f2404** [comment]
Hi, I'm having the same issue with xfce4-terminal ported to Gtk3: https://github.com/f2404/xfce4-terminal3/issues/12
Have you got any clues on how to resolve this? I have no ideas myself.
Thanks.

**Comment by rhoit** [comment]
this things happens in python too and i'm using Arch.

**Comment by f2404** [comment]
OK, I've found the cause for xfce4-terminal - it was `gtk_status_icon_set_name()` function.
See http://git.xfce.org/apps/xfce4-terminal/commit/?id=eff5e2db3dff7e586193e95156da24f2acf33eeb

**Comment by dorkbox** [comment]
**EXCELLENT.**

Thank you for figuring out what the cause was, I had been puzzled as to what it might be, as I had seen this on occasion when testing on various linux distros.  

I'll see about changing call ordering to make sure the icon exists before I set the name on it (to avoid this situation). Technically, it's supposed to all happen at once, but clearly that is not the case. I'm swamped at work at-the-moment, and as soon as I have some free time I'll see what I can do.

Thank you again for tracking this down.

**Comment by f2404** [comment]
You're welcome.
Please keep this issue updated, especially in case you are able to find a solution better than just removing the call.

**Comment by rhoit** [comment]
@f2404 thanks it was due to `Gtk.StatusIcon.set_name` in python too.

**Comment by dorkbox** [comment]
This should be fixed in the 3.0 Beta. It turns out that this gtk call is necessary in certain configurations (specifically when running under JavaFX), however -- when it's necessary, it doesn't cause this error to show, which incredibly strange...

3.0 beta is released as a "all-in-one" jar, for a variety of different tray types and configurations. I'm starting a new issue to track the progress for this. I definitely will need help testing in different Linux/Mac/Windows configurations (ie: I have no idea if this works in Windows 10, or the latest MacOsX)

I'm closing this issue and tracking everything in a new one. Please use Issue #22 for all related feedback, problems, etc.

**Comment by mczuba** [comment]
I'm still getting the issue with 1.12-5 -- it doesn't appear to break any functionality, but I'm wondering whether it's worth fixing myself? I'm surprised that after five years this hasn't been patched out.

**Comment by dorkbox** [comment]
:( I wish it were easy to fix the GDK bugs — if you fix it, please let me know, and I’ll include it!
